### ISSUE TITLE
Match undefined for Schema extend options

### ISSUE THREAD

**Issue by janat08** [loredanacirstea/simple-filter#1]
ReferenceError: Match is not defined
W20160618-21:36:30.519(6)? (STDERR)     at meteorInstall.lib.collections.js (lib/collections.js:6:22)

**Comment by loredanacirstea** [comment]
I built this app on Meteor 1.2.1. Meteor 1.3.x comes with a lot of breaking changes in dependencies. I have updated the Readme file with this info (thank you for pointing this out).

So, if you want to test it, use the 1.2.1 release.

**Comment by loredanacirstea** [comment]
I updated to Meteor 1.3.3.1 + updated all the packages and there was no issue.

Make sure you have the `check` package installed, like simple-filter has: https://github.com/loredanacirstea/simple-filter/blob/master/.meteor/packages#L25

See http://docs.meteor.com/api/check.html
